//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto
{
    using Proyecto.Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PruebaEntities2 : DbContext
    {
        public PruebaEntities2()
            : base("name=PruebaEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administracion> administracions { get; set; }
        public virtual DbSet<DetallePedido> detalle_pedido { get; set; }
        public virtual DbSet<Pedido> pedidoes { get; set; }
        public virtual DbSet<Producto> productoes { get; set; }
        public virtual DbSet<Usuario> usuarios { get; set; }
    }
}
